const products = [
  {
    id: 0,
    name: "Demaura Ring",
    base: "silver",
    stone: "emerald",
    price: 8500,
    initial: 8500,
    shop: "shop1",
    acessory: "ring",
    img: "./img/products/pict0.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 1,
    name: "Siplora Ring",
    base: "silver",
    stone: "diamond",
    price: 2300,
    initial: 2300,
    shop: "shop1",
    acessory: "ring",
    img: "./img/products/pict1.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 2,
    name: "Mayona Pingent",
    base: "silver",
    stone: "ruby",
    price: 11100,
    initial: 11100,
    shop: "shop1",
    acessory: "pingent",
    img: "./img/products/pict2.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 3,
    name: "Anemone Bracelet",
    base: "gold",
    stone: "diamond",
    price: 4300,
    initial: 4300,
    shop: "shop1",
    acessory: "bracelet",
    img: "./img/products/pict3.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 4,
    name: "Polly Earrings",
    base: "gold",
    stone: "diamond",
    price: 12750,
    initial: 12750,
    shop: "shop1",
    acessory: "earring",
    img: "./img/products/pict4.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 5,
    name: "Jaymelin Pingent",
    base: "silver",
    stone: "emerald",
    price: 8500,
    initial: 8500,
    shop: "shop1",
    acessory: "pingent",
    img: "./img/products/pict5.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 6,
    name: "Skopleos Ring",
    base: "gold",
    stone: "diamond",
    price: 22000,
    initial: 22000,
    shop: "shop1",
    acessory: "ring",
    img: "./img/products/pict6.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 7,
    name: "Denise Earrings",
    base: "silver",
    stone: "diamond",
    price: 13300,
    initial: 13300,
    shop: "shop1",
    acessory: "earring",
    img: "./img/products/pict7.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 8,
    name: "Antonella Ring",
    base: "silver",
    stone: "emerald",
    befor: 11000,
    price: 5500,
    initial: 5500,
    shop: "shop2",
    acessory: "ring",
    img: "./img/products/pict8.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 9,
    name: "Berceste Earrings",
    base: "silver",
    stone: "safira",
    befor: 15050,
    price: 7525,
    initial: 7525,
    shop: "shop2",
    acessory: "earrings",
    img: "./img/products/pict9.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 10,
    name: "Eberta Pingent",
    base: "silver",
    stone: "diamond",
    befor: 9500,
    price: 4750,
    initial: 4750,
    shop: "shop2",
    acessory: "pingent",
    img: "./img/products/pict10.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 11,
    name: "Ellen Bracelet",
    base: "gold",
    stone: "diamond",
    befor: 5000,
    price: 2500,
    initial: 2500,
    shop: "shop2",
    acessory: "bracelet",
    img: "./img/products/pict11.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 12,
    name: "Badhild Bracelet",
    base: "silver",
    stone: "emerald",
    befor: 7600,
    price: 3800,
    initial: 3800,
    shop: "shop2",
    acessory: "bracelet",
    img: "./img/products/pict12.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 13,
    name: "Arlenys Pingent",
    base: "gold",
    stone: "emerald",
    befor: 17000,
    price: 8500,
    initial: 8500,
    shop: "shop2",
    acessory: "pingent",
    img: "./img/products/pict13.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 14,
    name: "Eva Ring",
    base: "gold",
    stone: "ruby",
    befor: 22000,
    price: 11000,
    initial: 11000,
    shop: "shop2",
    acessory: "ring",
    img: "./img/products/pict14.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 15,
    name: "Dajana Earrings",
    base: "gold",
    stone: "diamond",
    befor: 13300,
    price: 6650,
    initial: 6650,
    shop: "shop2",
    acessory: "earrings",
    img: "./img/products/pict15.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 16,
    name: "Terenzia Ring",
    base: "gold",
    stone: "diamond",
    befor: 15500,
    price: 7750,
    initial: 7750,
    shop: "shop3",
    acessory: "ring",
    img: "./img/products/pict16.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 17,
    name: "Azurine Earrings",
    base: "silver",
    stone: "diamond",
    befor: 6600,
    price: 3300,
    initial: 3300,
    shop: "shop3",
    acessory: "earrings",
    img: "./img/products/pict17.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 18,
    name: "Arnadia Pingent",
    base: "silver",
    stone: "ruby",
    befor: 13000,
    price: 6500,
    initial: 6500,
    shop: "shop3",
    acessory: "pingent",
    img: "./img/products/pict18.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 19,
    name: "Sycamore Bracelet",
    base: "silver",
    stone: "ruby",
    befor: 3000,
    price: 1500,
    initial: 1500,
    shop: "shop3",
    acessory: "bracelet",
    img: "./img/products/pict19.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 20,
    name: "Perjant Bracelet",
    base: "silver",
    stone: "diamond",
    befor: 11300,
    price: 5650,
    initial: 5650,
    shop: "shop3",
    acessory: "bracelet",
    img: "./img/products/pict20.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 21,
    name: "Olga Pingent",
    base: "silver",
    stone: "diamond",
    befor: 8600,
    price: 4300,
    initial: 4300,
    shop: "shop3",
    acessory: "pingent",
    img: "./img/products/pict21.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 22,
    name: "Safira Ring",
    base: "silver",
    stone: "safira",
    befor: 10400,
    price: 5200,
    initial: 5200,
    shop: "shop3",
    acessory: "ring",
    img: "./img/products/pict22.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
  {
    id: 23,
    name: "Dilfigar Earrings",
    base: "gold",
    stone: "diamand",
    befor: 17000,
    price: 8500,
    initial: 8500,
    shop: "shop3",
    acessory: "earrings",
    img: "./img/products/pict23.png",
    descript:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, nobis consectetur labore sint, quod repudiandae nihil iusto reiciendis enim facilis iure qui cum doloremque non tempore expedita. Odio, perspiciatis fugit!",
  },
];
